apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres

type: Opaque 
data:
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cXdlcnR5

  ## codificar en base 64
  ## echo -n "postgres"  | base64

  ##decodificar en base 64
  ## echo "cG9zdGdyZXM="  | base64 -d