apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script-configmap
data:
  initdb.sh: |-
   #!/bin/bash
   set -e
   psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER santi WITH PASSWORD 'qwerty';
    CREATE DATABASE k8sapp;
    GRANT ALL PRIVILEGES ON DATABASE k8sapp TO santi;
   EOSQL